### ISSUE TITLE
Unable to install GridCal

### ISSUE THREAD

**Issue by bmitrauncc** [SanPen/GridCal#12]
Hi Sean,

I am trying to install GridCal in Win 10, but I keep facing the error, see screen shot, I have tried all the remedies with regards to it on the internet but nothing seems to work. Need your help...

![image](https://user-images.githubusercontent.com/34365438/33754988-b5bac6c4-dbbc-11e7-8f8f-16d1a517878c.png)

**Comment by SanPen** [comment]
Hi, unfortunately this is due to a bug in pip (I guess) because it does not install all the required packages upon GridCal setup as it should.

Observe the sentence 

> ModuleNotFoundError: No module names 'pyDOE'

This tells you that pyDOE is missing and you need to install it.

You fix this with `pip install pysot`

Do the same with the rest of the modules that it tell you that are missing.

I'll try to fix this but I have included in the setup file all that the documentation recommends, so I guess this is a bug of pip...

**Comment by bmitrauncc** [comment]
I installed all the missing modules, not sure how to handle this one.

![image](https://user-images.githubusercontent.com/34365438/33777440-d46d6328-dc12-11e7-96ab-f5a426dbf710.png)

**Comment by bmitrauncc** [comment]
Worked after downloading the file from the network...

Thanks for your help
