### ISSUE TITLE
Crash at large grids

### ISSUE THREAD

**Issue by yns0671** [SanPen/GridCal#325]
**Describe the bug**
We impported a 3000 bus system in order to try but the app is unsuable right now. Is it about graphic setings or something else. Maybe Gridcal is not for such large grids or we do something wrong. Can we fix that?

![Capture](https://github.com/user-attachments/assets/8f07ce24-e636-4b22-b279-d8b14e4e242b)

**Comment by SanPen** [comment]
Hi!

Generally, the issue with the graphics happens if you have many buses too close together. That is a Qt thing.

You have a couple of options:
- Don't generate a 3000 bus diagram, and generate smaller ones.
- Don't generate a schematic diagram and use a map diagram instead to visualize all the grid.
- Separate the nodes sufficiently so that they are displayed individually (plus button)

Let me know if it works

**Comment by yns0671** [comment]
it works better when i divide the grid into pieces and add circuits. thanks
